export const site = {
  name: "Tomiwa Philip",
  fullName: "Tomiwa Philip Oluwasanmi",
  role: "AI/ML Engineer · Full-Stack Web3 Developer · Entrepreneur",
  tagline: "I build engines that move trust and value.",
  description:
    "Tomiwa Philip is an AI/ML engineer, full-stack Web3 developer, and entrepreneur. 9+ years building production AI systems and blockchain settlement infrastructure — Vouchify, Zet.money, Mileston, Veridaq, Ivy. Currently founding Shakes Labs.",
  url: "https://tomiwaphilip.com",
  ogImage: "/og.png",
  locale: "en_US",
  location: "Abuja, Nigeria",
  email: "tomiwaphilip1100@gmail.com",
  socials: {
    x: "https://x.com/TomiwaIsGod",
    github: "https://github.com/TomiwaPhilip",
    shakeslabs: "https://shakeslabs.com",
  },
  keywords: [
    "Tomiwa Philip",
    "Tomiwa Philip Oluwasanmi",
    "AI Engineer",
    "Machine Learning Engineer",
    "Full Stack Developer",
    "Web3 Developer",
    "Blockchain Engineer",
    "Solidity Developer",
    "Smart Contracts",
    "Settlement Engine",
    "Vouchify",
    "Zet.money",
    "Mileston",
    "Veridaq",
    "Shakes Labs",
    "Nigeria",
    "Abuja",
    "CTO",
    "Entrepreneur",
  ],
} as const;
