export const site = {
  name: "Tomiwa Philip",
  fullName: "Tomiwa Philip",
  role: "Founder · CEO · CTO at Shakes Labs · AI/ML Engineer · Full-Stack Web3 Developer",
  tagline: "I build engines that move trust and value.",
  description:
    "Tomiwa Philip is the founder, CEO, and CTO of Shakes Labs — a long-term technology partnership studio shipping AI, Web3, mobile, and web. 9+ years building production systems across Vouchify, Zet.money, Mileston, Veridaq, and Ivy.",
  url: "https://www.tomiwaphilip.com",
  ogImage: "/og.png",
  locale: "en_US",
  location: "Abuja, Nigeria",
  email: "tomiwa@shakeslabs.com",
  socials: {
    x: "https://x.com/TomiwaIsGod",
    github: "https://github.com/TomiwaPhilip",
    shakeslabs: "https://www.shakeslabs.com",
  },
  keywords: [
    "Tomiwa Philip",
    "Shakes Labs",
    "Shakes Labs Founder",
    "Shakes Labs CEO",
    "Shakes Labs CTO",
    "AI Engineer",
    "Machine Learning Engineer",
    "Full Stack Developer",
    "Web3 Developer",
    "Blockchain Engineer",
    "Solidity Developer",
    "Smart Contracts",
    "Settlement Engine",
    "Vouchify",
    "Zet.money",
    "Mileston",
    "Veridaq",
    "Nigeria",
    "Abuja",
    "Founder",
    "CTO",
    "CEO",
    "Entrepreneur",
  ],
} as const;
